<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hash</title>
</head>
<body>
    <form method="post" action="decrypt_password.php">
        <label for="password">Password</label>
        <input type="password" id="password" name="password" />
        
        <label for="hash">Mot de passe chiffré :</label>
        <input type="text" id="hash" name="hash" required>
    
        <button type="submit">Valider</button>
    </form>
</body>
</html>



